# Generated by Django 2.2.3 on 2019-10-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.PositiveIntegerField(default=1)),
                ('ile_zlecen', models.PositiveIntegerField(default=0)),
                ('ostatnie_zlecenie', models.CharField(default=0, max_length=30)),
                ('ostatnia_przesylka', models.CharField(default=1, max_length=30)),
                ('ostatni_produkt', models.CharField(default=1, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=100)),
                ('is_file', models.BooleanField()),
                ('is_directory', models.BooleanField()),
                ('is_main', models.BooleanField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('order_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=50)),
                ('shipment_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['condition'],
            },
        ),
        migrations.CreateModel(
            name='PackageKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='PackageMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['product_type'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('order_name', models.CharField(max_length=100)),
                ('shipment_id', models.PositiveIntegerField()),
                ('sender', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=50)),
                ('package_number', models.CharField(max_length=50)),
                ('accepted', models.CharField(max_length=120)),
                ('product_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order_id', 'shipment_id')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('order_name', models.CharField(max_length=100)),
                ('shipment_id', models.PositiveIntegerField()),
                ('product_id', models.PositiveIntegerField()),
                ('EAN', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('pieces', models.PositiveIntegerField()),
                ('package_condition', models.CharField(default='Stan opakowania', max_length=100)),
                ('package_type', models.CharField(default='Typ opakowania', max_length=100)),
                ('package_kind', models.CharField(default='Rodzaj opakowania', max_length=100)),
                ('package_material', models.CharField(default='Material opakowania', max_length=100)),
                ('product_type', models.CharField(default='Typ produktu', max_length=100)),
                ('localization', models.CharField(max_length=100)),
                ('has_relation', models.BooleanField()),
                ('EAN2', models.CharField(max_length=20)),
                ('pieces2', models.PositiveIntegerField()),
                ('has_attributes', models.BooleanField(default=True)),
                ('done', models.BooleanField(default=False)),
                ('weight_from_label', models.PositiveIntegerField(default=0)),
                ('capacity_from_label', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order_id', 'shipment_id', 'product_id')},
            },
        ),
    ]
