# Generated by Django 2.2.6 on 2019-12-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyTube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('canal', models.CharField(max_length=100)),
                ('positive_voices', models.PositiveIntegerField()),
                ('negative_voices', models.PositiveIntegerField()),
                ('uploaded_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhenFaceAppears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeared_start', models.TimeField()),
                ('appeared_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TyTube.Clips', verbose_name='video')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PackageCondition',
        ),
        migrations.DeleteModel(
            name='PackageKind',
        ),
        migrations.DeleteModel(
            name='PackageMaterial',
        ),
        migrations.DeleteModel(
            name='PackageType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
