# Generated by Django 2.2.6 on 2019-11-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TyTube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('canal', models.CharField(max_length=100)),
                ('positive_voices', models.PositiveIntegerField()),
                ('negative_voices', models.PositiveIntegerField()),
                ('uploaded_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='litry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(default='tak', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='EAN2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_attributes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='WhenFaceAppears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeared_start', models.TimeField()),
                ('appeared_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TyTube.Clips', verbose_name='video')),
            ],
        ),
    ]
