# Generated by Django 2.2.6 on 2019-11-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyTube', '0002_auto_20191126_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='uploaded_date',
            field=models.DateField(null=True),
        ),
    ]
