# Generated by Django 2.2.6 on 2019-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyTube', '0002_auto_20191215_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clips',
            old_name='uploaded_date',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='clips',
            name='face_on_screen_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clips',
            name='face_recognized_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
